version: "2"
services:
  goodbot-app:
    image: "node:8"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/home/node/app
    expose:
      - "8081"
    links:
      - "mysql"
    command: "node index.js"
    depends_on:
      - mysql
  mysql:
    container_name: goodbot-db
    image: mysql:8.0.19
    volumes:
      - ./docker/db:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --sql_mode=""
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root_password
